@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdGFuZGFyZENsYWltcyI6eyJleHAiOjE3Mjc4MTQ0MTZ9LCJpZCI6IjZhMDQxY2RkLWRlZGYtNDRkZC05OGZjLWViYWE1MDZkNWNhYiIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.xyJOky16dZqBlhhUySdgslnEzyyZBSYdxyUz2BoeoDA
@id=6a041cdd-dedf-44dd-98fc-ebaa506d5cab
@eventId=3a051b95-0a87-4924-821d-53caf0bfd937

### Fetch User
GET http://localhost:8080/users/{{id}}
Authorization: Bearer {{token}}

### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "admin",
  "password": "password123",
  "role": "admin"
}

### Login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}

### Update User (Join Event)
PUT http://localhost:8080/users/{{eventId}}
Authorization: Bearer {{token}}

### Get User's Events
GET http://localhost:8080/users/{{id}}/events
Authorization: Bearer {{token}}
