version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=:8080
      - MYSQL_DB=emma
      - MYSQL_TCP=@tcp(db:3306)
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - JWT_SECRET=my_secret_key
      - JWT_EXPIRY_TIME=24h

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=emma
      - MYSQL_HOST=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
